[package]
name = "faces"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", default-features = true }
winit = "0.28.7"
bevy_rapier2d = "0.22.0"
rand = "0.8.5"
ron = "0.8.1"
serde = "1.0.189"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3